apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: temp-jenkins
  template:
    metadata:
      labels:
        app: temp-jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins:2.60.3
        ports:
          - name: cicd-master
            containerPort: 8080
        volumeMounts:
          - name: jenkins-data  # Corrected volume name
            mountPath: /var/jenkins_home
      volumes:  # Corrected indentation
        - name: jenkins-data  # Corrected volume name
          nfs:
            server: 192.168.147.129
            path: /var/tmp/nfsshared

---
apiVersion: v1
kind: Service
metadata:
  name: test-nodeport
spec:
  selector:
    app: temp-jenkins
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort