apiVersion: v1
kind: Pod
metadata:
  name: testdir
  labels:
    name: test
    env: UAT
spec:
  containers:
    - name: write-container
      image: ubutnu
      command: ["sh", "-c"]
      args: ["while true; do date >> /var/log/index.html; sleep 10; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /var/log
    - name: serving-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      nfs:
        server: 192.168.147.129
        path: /var/tmp/nfsshared

